# Workflow for building and deploying GitHub Pages site
name: Documentation

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["PaperPreparation"]

  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Julia Environment
        uses: julia-actions/setup-julia@latest
        with:
          version: '1.7'
      - name: Install dependencies
        # run: julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.add("Documenter"); Pkg.instantiate()'
        run: julia --project=docs -e 'using Pkg; Pkg.add("Documenter"); Pkg.instantiate()'
      - name: Build Documents through Documenter.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=docs docs/make.jl
        
